### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yyhoshino** [yyhoshino/protospace-38595_id#1]
# URL

https://protospace-38595.herokuapp.com/

**Comment by ghost** [comment]
@yyhoshino さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！
今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by yyhoshino** [comment]
修正が何かしらあると思ったのですが！！よかったです！ありがとうございます！！頑張ります！！
